export const STARTING_POINT_QUESTIONS = [
  {
    id: "experience",
    prompt: "How much code have you written on your own?",
    kind: "self-report",
    options: [
      { label: "I am brand new and want the first step.", level: "absolute_beginner" },
      { label: "I have seen examples, but I am not sure how to write my own yet.", level: "syntax_beginner" },
      { label: "I can write small programs with help.", level: "control_flow_practice" },
      { label: "I can solve small problems and want to move faster.", level: "code_ready" },
    ],
  },
  {
    id: "variable",
    prompt: "Which Python line stores the number 5 in a name called score?",
    kind: "graded",
    skill: "syntax",
    options: [
      { code: "score = 5", level: "syntax_beginner", correct: true },
      { code: "score == 5", level: "debugging_practice" },
      { code: "print(5)", level: "syntax_beginner" },
      { code: "score + 5", level: "absolute_beginner" },
    ],
  },
  {
    id: "output",
    prompt: "In Python, what does print usually do?",
    kind: "graded",
    skill: "syntax",
    code: 'print("Go Bears")',
    options: [
      { label: "Shows Go Bears on the screen.", level: "syntax_beginner", correct: true },
      { label: "Stores Go Bears for later.", level: "syntax_beginner" },
      { label: "Repeats Go Bears many times.", level: "control_flow_practice" },
      { label: "Chooses whether Go Bears is true.", level: "control_flow_practice" },
    ],
  },
  {
    id: "conditional",
    prompt: "Which Python line asks whether a score is at least 70?",
    kind: "graded",
    skill: "control_flow",
    options: [
      { code: "if score >= 70:", level: "control_flow_practice", correct: true },
      { code: "score = 70", level: "syntax_beginner" },
      { code: "for score in 70:", level: "control_flow_practice" },
      { code: "print(score)", level: "syntax_beginner" },
    ],
  },
  {
    id: "repetition",
    prompt: "Which situation sounds most like repetition?",
    kind: "graded",
    skill: "control_flow",
    options: [
      { label: "Add up every price in a grocery list.", level: "control_flow_practice", correct: true },
      { label: "If the grade is at least 70, show passing.", level: "control_flow_practice" },
      { label: "Store a student's name in a variable.", level: "syntax_beginner" },
      { label: "Fix a program after it gives the wrong answer.", level: "debugging_practice" },
    ],
  },
  {
    id: "function",
    prompt: "What is a function mainly for?",
    kind: "graded",
    skill: "functions",
    options: [
      { label: "Giving a name to a group of steps so you can use them again.", level: "functions_practice", correct: true },
      { label: "Making every program run faster automatically.", level: "absolute_beginner" },
      { label: "Saving a value that never changes.", level: "syntax_beginner" },
      { label: "Showing an error when something goes wrong.", level: "debugging_practice" },
    ],
  },
  {
    id: "collection",
    prompt: "A student wants to keep several assignment scores together. Which idea fits best?",
    kind: "graded",
    skill: "data_structures",
    options: [
      { label: "A collection of values.", level: "data_structures_intro", correct: true },
      { label: "One printed message.", level: "syntax_beginner" },
      { label: "A single yes-or-no choice.", level: "control_flow_practice" },
      { label: "The name of the program.", level: "absolute_beginner" },
    ],
  },
  {
    id: "debugging",
    prompt: "Your program gives the wrong answer. What is the best first debugging step?",
    kind: "graded",
    skill: "debugging",
    options: [
      { label: "Run it again with a small example and check each step.", level: "debugging_practice", correct: true },
      { label: "Delete the whole program immediately.", level: "absolute_beginner" },
      { label: "Add random changes until it works once.", level: "debugging_practice" },
      { label: "Assume the computer made a mistake.", level: "absolute_beginner" },
    ],
  },
  {
    id: "trace_loop",
    prompt: "A program checks four temperatures and counts each one above 80. What should happen while it runs?",
    kind: "graded",
    skill: "control_flow",
    bridge: true,
    options: [
      { label: "Look at each temperature and update the count only when the condition is true.", level: "code_ready", correct: true },
      { label: "Only look at the first temperature.", level: "syntax_beginner" },
      { label: "Stop as soon as one temperature is above 80.", level: "control_flow_practice" },
      { label: "Print every temperature without checking it.", level: "syntax_beginner" },
    ],
  },
  {
    id: "learning_preference",
    prompt: "When learning a new programming topic, what feels most helpful right now?",
    kind: "self-report",
    options: [
      { label: "Start from the very beginning with plain examples.", level: "absolute_beginner", confidence: "low" },
      { label: "Practice storing values and showing results.", level: "syntax_beginner", confidence: "low" },
      { label: "Practice choices, repetition, and small problem steps.", level: "control_flow_practice", confidence: "medium" },
      { label: "Jump into challenge problems and review only when stuck.", level: "advanced_ready", confidence: "high" },
    ],
  },
];
